import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { useGetProducts } from '@/hooks/useGetProducts';
import { Carousel } from 'react-responsive-carousel';
import 'react-responsive-carousel/lib/styles/carousel.min.css';
import Image from 'next/image';
import imageLoader from '@/utils/imageLoader';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    router.push('/shop');
  }, []);
  const { isLoading, data } = useGetProducts();
  if (!isLoading) console.log(data?.slice(2));

  if (isLoading)
    return (
      <div className={styles.loadingContainer}>
        <div className={styles.loadingSpinner}></div>
      </div>
    );
  const featured = data?.slice(0, 2);
  console.log(featured);
  // console.log('RESPONSE', JSON.parse(products));

  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.mainContent}>
          <div className={styles.logoCategories}>
            <p>LOGO</p>
            <Link href={'/shop'} className={styles.viewCategories}>
              View Categories
            </Link>
          </div>
          <Carousel
            infiniteLoop={true}
            showStatus={false}
            className={styles.carousel}
            autoPlay
            showThumbs={false}
          >
            {data?.slice(0, 4).map((product) => {
              return (
                <div className={styles.imageContainer} key={product.id}>
                  <Image
                    src={product.url}
                    width={250}
                    height={350}
                    alt={product.name}
                    unoptimized
                    loader={imageLoader}
                  />
                  <p className="legend">{product.name}</p>
                </div>
              );
            })}
          </Carousel>
        </section>
        {/* <section className={styles.offers}>
          <p>OFFERS</p>
          <Button variant="contained">Hello BUTTON</Button>
        </section> */}
      </main>
    </>
  );
}

// export const getServerSideProps = async () => {
//   const p = await prisma.product.findMany();
//   const products = JSON.stringify(p);
//   // console.log('ACA P', p);
//   return { props: { products } };
// };
